from datetime import datetime, timezone

from common_py.schemas import (
    AlertItem,
    AlertSeverity,
    AlertStatus,
    AlertType,
    BeforeAfterAssets,
    ConditionsSummaryItem,
    ConnectivityState,
    DataConfidence,
    EnvironmentalField,
    EnvironmentalFieldRange,
    EnvironmentalFieldType,
    EnvironmentalRenderType,
    EnvironmentalRiverPath,
    EnvironmentalTrend,
    EnvironmentalVectorSample,
    EventMetric,
    EventPreview,
    EventPreviewMetric,
    GeoPosition,
    IncidentDetail,
    LayerDefinition,
    LayerGroup,
    NarrativeEventType,
    NarrativeScene,
    NarrativeSceneCamera,
    NarrativeSceneKind,
    NarrativeStatus,
    NarrativeTone,
    NarrativeVisualState,
    NaturalEventCategory,
    NaturalEventEntity,
    OperationalStatus,
    ProvinceState,
    TimelineScene,
)

NOW = datetime.now(timezone.utc)
TIMELINE_START = datetime(2026, 5, 20, 18, 0, tzinfo=timezone.utc)


def point(lat: float, lng: float) -> GeoPosition:
    return GeoPosition(lat=lat, lng=lng)


STATUS = OperationalStatus(
    province_state=ProvinceState.ATTENTION,
    active_alert_count=4,
    wildfire_count=1,
    hydric_risk_level=AlertSeverity.HIGH,
    last_updated_at=NOW,
    connectivity_state=ConnectivityState.LIVE,
    headline="Crecida rapida en cuencas del norte y focos termicos aislados en Yungas.",
)

ALERTS = [
    AlertItem(
        id="flood-yala-001",
        type=AlertType.FLOOD_RISK,
        severity=AlertSeverity.CRITICAL,
        title="Crecida rapida detectada",
        short_message="Escorrentia intensa en Yala.",
        long_message="Se detecto incremento hidrico sostenido durante 48 horas con suelo saturado.",
        location_name="Yala · Cuenca norte",
        geometry={"type": "Point", "coordinates": [-65.48, -24.11]},
        centroid={"lat": -24.11, "lng": -65.48},
        created_at=NOW,
        status=AlertStatus.NEW,
        recommended_actions=["Activar monitoreo local", "Verificar rutas secundarias", "Preparar aviso preventivo"],
        impact_summary={
            "population": "3.2k personas expuestas",
            "infrastructure": "2 escuelas y 1 centro de salud cercano",
            "routes": "Ruta provincial 4 con riesgo de corte",
        },
        factors=["lluvia intensa", "saturacion del suelo", "pendiente critica"],
        region="Yala",
    ),
    AlertItem(
        id="wildfire-yungas-003",
        type=AlertType.WILDFIRE,
        severity=AlertSeverity.HIGH,
        title="Anomalia termica persistente",
        short_message="Foco termico activo en Yungas sur.",
        long_message="El cluster FIRMS mantiene persistencia superior al umbral de vigilancia.",
        location_name="Yungas sur",
        geometry={"type": "Point", "coordinates": [-64.85, -24.27]},
        centroid={"lat": -24.27, "lng": -64.85},
        created_at=NOW,
        status=AlertStatus.NEW,
        recommended_actions=["Cruzar con brigadas disponibles", "Revisar direccion del viento"],
        impact_summary={
            "population": "Baja exposicion poblacional",
            "infrastructure": "Area boscosa con senderos y tendido menor",
            "routes": "Acceso rural en vigilancia",
        },
        factors=["anomalia termica", "humedad baja", "cobertura vegetal continua"],
        region="Yungas",
    ),
]

LAYERS = [
    LayerDefinition(
        id="ndwi",
        group=LayerGroup.RISK,
        label="Agua superficial",
        technical_name="NDWI",
        visible_by_default=True,
        available_time_ranges=["72h", "30d"],
        legend=[{"label": "alto", "color": "#27B3FF"}],
    ),
    LayerDefinition(
        id="flood-risk",
        group=LayerGroup.RISK,
        label="Riesgo hidrico",
        technical_name="hydric-risk",
        visible_by_default=True,
        available_time_ranges=["24h", "72h"],
        legend=[{"label": "critico", "color": "#F04452"}],
    ),
    LayerDefinition(
        id="firms",
        group=LayerGroup.ENVIRONMENT,
        label="Focos termicos",
        technical_name="FIRMS",
        visible_by_default=True,
        available_time_ranges=["24h", "7d"],
        legend=[{"label": "activo", "color": "#F04452"}],
    ),
]

TIMELINE = [
    TimelineScene(
        timestamp=TIMELINE_START,
        available_layers=["ndwi", "flood-risk", "routes"],
        freshness="validado",
        comparison_supported=True,
    ),
    TimelineScene(
        timestamp=TIMELINE_START.replace(day=21),
        available_layers=["ndwi", "firms", "routes"],
        freshness="reciente",
        comparison_supported=True,
    ),
    TimelineScene(
        timestamp=TIMELINE_START.replace(day=22),
        available_layers=["ndwi", "flood-risk", "firms", "routes"],
        freshness="live",
        comparison_supported=True,
    ),
]

INCIDENTS = {
    alert.id: IncidentDetail(
        alert=alert,
        before_after_assets={"before": "Escena -48h", "after": "Escena actual"},
        mini_timeline=TIMELINE[-3:],
    )
    for alert in ALERTS
}

ENVIRONMENTAL_FIELDS = [
    EnvironmentalField(
        id="field-river-yala-stage",
        kind=EnvironmentalFieldType.RIVER_STAGE,
        field_type=EnvironmentalRenderType.RIVER_STATE,
        title="Nivel hidrometrico del rio Yala",
        label="Rio Yala",
        metric_name="river_stage",
        unit="m",
        current_value=3.8,
        change_24h=1.2,
        observed_at=NOW,
        severity=AlertSeverity.CRITICAL,
        source="hydro-sensor-network",
        sources=["hydro-sensor-network", "provincial-hydrology"],
        region="Yala",
        layer_id="flood-risk",
        geometry={
            "type": "LineString",
            "coordinates": [[-65.53, -24.09], [-65.48, -24.11], [-65.42, -24.14]],
        },
        centroid=point(-24.11, -65.48),
        location=point(-24.11, -65.48),
        trend=EnvironmentalTrend.RISING,
        value_range=EnvironmentalFieldRange(min=2.1, max=4.3, focus=3.8),
        summary="El nivel del rio supera la banda de vigilancia y acelera en las ultimas 6 horas.",
        confidence=DataConfidence.OBSERVED,
        related_event_ids=["event-flood-yala-20260522"],
        legend=[{"label": "critico", "color": "#27B3FF"}],
        paths=[
            EnvironmentalRiverPath(
                coordinates=[(-65.53, -24.09), (-65.48, -24.11), (-65.42, -24.14)],
                severity=AlertSeverity.CRITICAL,
            )
        ],
    ),
    EnvironmentalField(
        id="field-rain-yala-anomaly",
        kind=EnvironmentalFieldType.RAINFALL_ANOMALY,
        field_type=EnvironmentalRenderType.RAIN,
        title="Anomalia de precipitacion acumulada",
        label="Lluvia acumulada",
        metric_name="rainfall_anomaly",
        unit="mm",
        current_value=148.0,
        change_24h=32.0,
        observed_at=NOW,
        severity=AlertSeverity.HIGH,
        source="chirps-daily",
        sources=["chirps-daily", "gpm-imerg"],
        region="Yala",
        layer_id="ndwi",
        geometry={
            "type": "Polygon",
            "coordinates": [
                [[-65.57, -24.18], [-65.39, -24.18], [-65.39, -24.02], [-65.57, -24.02], [-65.57, -24.18]]
            ],
        },
        centroid=point(-24.11, -65.48),
        location=point(-24.11, -65.48),
        trend=EnvironmentalTrend.RISING,
        value_range=EnvironmentalFieldRange(min=68.0, max=160.0, focus=148.0),
        summary="La lluvia acumulada de 24 horas se mantiene por encima del percentil operativo esperado.",
        confidence=DataConfidence.MIXED,
        related_event_ids=["event-flood-yala-20260522", "event-landslide-volcan-20260522"],
        legend=[{"label": "alto", "color": "#27B3FF"}],
        samples=[
            EnvironmentalVectorSample(lat=-24.16, lng=-65.54, dx=0.05, dy=0.04, intensity=0.64),
            EnvironmentalVectorSample(lat=-24.09, lng=-65.47, dx=0.03, dy=0.05, intensity=0.82),
            EnvironmentalVectorSample(lat=-23.93, lng=-65.38, dx=0.02, dy=0.04, intensity=0.58),
        ],
    ),
    EnvironmentalField(
        id="field-thermal-yungas-cluster",
        kind=EnvironmentalFieldType.THERMAL_ACTIVITY,
        field_type=EnvironmentalRenderType.FIRE,
        title="Cluster termico Yungas sur",
        label="Focos FIRMS",
        metric_name="thermal_hotspots",
        unit="detections",
        current_value=7.0,
        change_24h=3.0,
        observed_at=NOW,
        severity=AlertSeverity.HIGH,
        source="firms",
        sources=["firms", "sentinel-2-thermal"],
        region="Yungas",
        layer_id="firms",
        geometry={
            "type": "Polygon",
            "coordinates": [
                [[-64.93, -24.33], [-64.76, -24.33], [-64.76, -24.21], [-64.93, -24.21], [-64.93, -24.33]]
            ],
        },
        centroid=point(-24.27, -64.85),
        location=point(-24.27, -64.85),
        trend=EnvironmentalTrend.RISING,
        value_range=EnvironmentalFieldRange(min=1.0, max=8.0, focus=7.0),
        summary="Persisten detecciones termicas con continuidad espacial y baja humedad relativa.",
        confidence=DataConfidence.OBSERVED,
        related_event_ids=["event-wildfire-yungas-20260522"],
        legend=[{"label": "activo", "color": "#F04452"}],
    ),
    EnvironmentalField(
        id="field-soil-volcan-moisture",
        kind=EnvironmentalFieldType.SOIL_MOISTURE,
        field_type=EnvironmentalRenderType.FLOOD_RISK,
        title="Humedad superficial en abanicos aluviales",
        label="Humedad de ladera",
        metric_name="soil_moisture",
        unit="fraction",
        current_value=0.71,
        change_24h=0.14,
        observed_at=NOW,
        severity=AlertSeverity.MEDIUM,
        source="smap-l3",
        sources=["smap-l3", "slope-susceptibility-model"],
        region="Volcan",
        layer_id="flood-risk",
        geometry={
            "type": "Polygon",
            "coordinates": [
                [[-65.46, -23.96], [-65.30, -23.96], [-65.30, -23.84], [-65.46, -23.84], [-65.46, -23.96]]
            ],
        },
        centroid=point(-23.90, -65.38),
        location=point(-23.90, -65.38),
        trend=EnvironmentalTrend.RISING,
        value_range=EnvironmentalFieldRange(min=0.22, max=0.84, focus=0.71),
        summary="La humedad superficial mantiene las laderas cercanas al umbral de remocion menor.",
        confidence=DataConfidence.MIXED,
        related_event_ids=["event-landslide-volcan-20260522"],
        legend=[{"label": "alerta", "color": "#E8C547"}],
    ),
]

NARRATIVE_FIELD_MAP = {field.id: field for field in ENVIRONMENTAL_FIELDS}

EVENT_PREVIEWS = [
    EventPreview(
        id="preview-flood-yala",
        event_id="event-flood-yala-20260522",
        title="Yala bajo presion hidrica",
        subtitle="Cuenca norte",
        category=NaturalEventCategory.FLOOD,
        kind=NaturalEventCategory.FLOOD,
        event_type=NarrativeEventType.FLOOD_RISK,
        severity=AlertSeverity.CRITICAL,
        status=AlertStatus.NEW,
        kicker="Evento prioritario",
        location_name="Yala · Cuenca norte",
        region="Yala",
        summary="El nivel del rio y la lluvia acumulada sostienen riesgo de desborde local.",
        observed_at=NOW,
        updated_at=NOW,
        primary_scene_id="scene-yala-overview-live",
        field_ids=["field-river-yala-stage", "field-rain-yala-anomaly"],
        centroid=point(-24.11, -65.48),
        primary_metric=EventPreviewMetric(label="Nivel del rio", value="3.8 m", tone="critical"),
        primaryMetric="3.8 m sobre banda de riesgo",
        change="+1.2 m",
        direction="Escorrentia SSE",
        chips=["lluvia intensa", "cauce en ascenso", "rutas sensibles"],
    ),
    EventPreview(
        id="preview-wildfire-yungas",
        event_id="event-wildfire-yungas-20260522",
        title="Persistencia termica en Yungas",
        subtitle="Ladera sur",
        category=NaturalEventCategory.WILDFIRE,
        kind=NaturalEventCategory.WILDFIRE,
        event_type=NarrativeEventType.WILDFIRE,
        severity=AlertSeverity.HIGH,
        status=AlertStatus.NEW,
        kicker="Seguimiento activo",
        location_name="Yungas sur",
        region="Yungas",
        summary="El cluster FIRMS suma detecciones consecutivas sobre cobertura continua.",
        observed_at=NOW,
        updated_at=NOW,
        primary_scene_id="scene-yungas-thermal-response",
        field_ids=["field-thermal-yungas-cluster"],
        centroid=point(-24.27, -64.85),
        primary_metric=EventPreviewMetric(label="Focos", value="7 detecciones", tone="warning"),
        primaryMetric="7 detecciones termicas",
        change="+3 focos",
        direction="Viento NE moderado",
        chips=["vegetacion continua", "humedad baja", "brigadas cercanas"],
    ),
    EventPreview(
        id="preview-landslide-volcan",
        event_id="event-landslide-volcan-20260522",
        title="Laderas sensibles en Volcan",
        subtitle="Abanicos aluviales",
        category=NaturalEventCategory.LANDSLIDE,
        kind=NaturalEventCategory.LANDSLIDE,
        event_type=NarrativeEventType.RAINFALL,
        severity=AlertSeverity.MEDIUM,
        status=AlertStatus.ACKNOWLEDGED,
        kicker="Vigilancia preventiva",
        location_name="Volcan · abanicos aluviales",
        region="Volcan",
        summary="Humedad superficial y acumulado reciente sostienen una ventana de vigilancia.",
        observed_at=NOW,
        updated_at=NOW,
        primary_scene_id="scene-volcan-slope-watch",
        field_ids=["field-rain-yala-anomaly", "field-soil-volcan-moisture"],
        centroid=point(-23.90, -65.38),
        primary_metric=EventPreviewMetric(label="Humedad", value="0.71", tone="info"),
        primaryMetric="0.71 fraccion de humedad",
        change="+0.14",
        direction=None,
        chips=["banquinas expuestas", "lluvia reciente", "drenajes en revision"],
    ),
]

EVENT_PREVIEW_MAP = {preview.event_id: preview for preview in EVENT_PREVIEWS}

NATURAL_EVENTS = [
    NaturalEventEntity(
        id="event-flood-yala-20260522",
        title="Crecida rapida en Yala",
        category=NaturalEventCategory.FLOOD,
        kind=NaturalEventCategory.FLOOD,
        event_type=NarrativeEventType.FLOOD_RISK,
        severity=AlertSeverity.CRITICAL,
        status=AlertStatus.NEW,
        summary="La combinacion de lluvia acumulada y nivel hidrometrico eleva el riesgo de desborde local.",
        short_message="Escorrentia intensa y cauce en ascenso en Yala.",
        description="El corredor del rio Yala concentra aumento hidrico sostenido, suelo saturado y accesos secundarios comprometidos en la cuenca norte.",
        long_message="La narrativa territorial indica presion hidrica sostenida por lluvia acumulada, respuesta rapida del cauce y puntos viales sensibles junto al rio.",
        narrative_label="Escalada hidrica",
        narrative_summary="El rio Yala gana velocidad y altura mientras la lluvia mantiene la cuenca cargada; el foco operativo esta en anticipar cortes y avisos riberenos.",
        location_name="Yala · Cuenca norte",
        region="Yala",
        observed_at=NOW,
        started_at=NOW,
        updated_at=NOW,
        geometry={
            "type": "Polygon",
            "coordinates": [
                [[-65.57, -24.18], [-65.39, -24.18], [-65.39, -24.02], [-65.57, -24.02], [-65.57, -24.18]]
            ],
        },
        centroid=point(-24.11, -65.48),
        location=point(-24.11, -65.48),
        confidence_score=0.93,
        confidence=DataConfidence.OBSERVED,
        source_signals=["river_stage", "rainfall_anomaly", "ndwi"],
        sources=["hydro-sensor-network", "chirps-daily", "ndwi-processor"],
        recommended_actions=[
            "Priorizar aviso preventivo en barrios riberenos",
            "Verificar transitabilidad de rutas secundarias",
            "Mantener seguimiento cada 15 minutos",
        ],
        impact_summary={
            "population": "3.2k personas expuestas",
            "infrastructure": "2 escuelas y 1 centro de salud cercano",
            "routes": "Ruta provincial 4 con riesgo de corte",
        },
        drivers=["lluvia intensa", "cauce en ascenso", "saturacion del suelo"],
        factors=["lluvia intensa", "saturacion del suelo", "pendiente critica"],
        metrics=[
            EventMetric(id="river-stage", label="Nivel del rio", value="3.8", unit="m", trend=EnvironmentalTrend.RISING, emphasis="primary"),
            EventMetric(id="rain-24h", label="Lluvia 24h", value="148", unit="mm", trend=EnvironmentalTrend.RISING, emphasis="secondary"),
        ],
        related_field_ids=["field-river-yala-stage", "field-rain-yala-anomaly"],
        linked_field_ids=["field-river-yala-stage", "field-rain-yala-anomaly"],
        related_scene_ids=["scene-yala-overview-live", "scene-provincial-priority-board"],
        related_fields=[
            NARRATIVE_FIELD_MAP["field-river-yala-stage"],
            NARRATIVE_FIELD_MAP["field-rain-yala-anomaly"],
        ],
        before_after_assets=BeforeAfterAssets(before="Rio Yala hace 48h", after="Rio Yala ahora"),
        preview=EVENT_PREVIEW_MAP["event-flood-yala-20260522"],
        visual_state=NarrativeVisualState(pulse=True, highlighted=True),
    ),
    NaturalEventEntity(
        id="event-wildfire-yungas-20260522",
        title="Focos termicos persistentes en Yungas sur",
        category=NaturalEventCategory.WILDFIRE,
        kind=NaturalEventCategory.WILDFIRE,
        event_type=NarrativeEventType.WILDFIRE,
        severity=AlertSeverity.HIGH,
        status=AlertStatus.NEW,
        summary="El cluster FIRMS sostiene detecciones consecutivas sobre cobertura vegetal continua.",
        short_message="Persisten focos sobre cobertura continua.",
        description="Se observa persistencia termica con condiciones secas y accesibilidad parcial para brigadas rurales en Yungas sur.",
        long_message="La escena combina focos termicos persistentes, humedad baja y viento moderado con accesos rurales bajo monitoreo.",
        narrative_label="Fuego en propagacion potencial",
        narrative_summary="Los focos no se expanden aun de forma masiva, pero la continuidad de la vegetacion y el viento moderado sostienen un escenario de escalada.",
        location_name="Yungas sur",
        region="Yungas",
        observed_at=NOW,
        started_at=NOW,
        updated_at=NOW,
        geometry={
            "type": "Polygon",
            "coordinates": [
                [[-64.93, -24.33], [-64.76, -24.33], [-64.76, -24.21], [-64.93, -24.21], [-64.93, -24.33]]
            ],
        },
        centroid=point(-24.27, -64.85),
        location=point(-24.27, -64.85),
        confidence_score=0.88,
        confidence=DataConfidence.OBSERVED,
        source_signals=["firms", "wind_forecast"],
        sources=["firms", "sentinel-2-thermal", "provincial-brigades"],
        recommended_actions=[
            "Cruzar focos con disponibilidad de brigadas",
            "Monitorear direccion de viento predominante",
            "Restringir acceso no esencial en senderos cercanos",
        ],
        impact_summary={
            "population": "Baja exposicion poblacional",
            "infrastructure": "Area boscosa con senderos y tendido menor",
            "routes": "Acceso rural en vigilancia",
        },
        drivers=["anomalia termica", "humedad baja", "viento moderado"],
        factors=["anomalia termica", "humedad baja", "cobertura vegetal continua"],
        metrics=[
            EventMetric(id="thermal-detections", label="Focos", value="7", unit="detections", trend=EnvironmentalTrend.RISING, emphasis="primary"),
            EventMetric(id="wind", label="Viento", value="18", unit="km/h", trend=EnvironmentalTrend.STABLE, emphasis="secondary"),
        ],
        related_field_ids=["field-thermal-yungas-cluster"],
        linked_field_ids=["field-thermal-yungas-cluster"],
        related_scene_ids=["scene-yungas-thermal-response", "scene-provincial-priority-board"],
        related_fields=[NARRATIVE_FIELD_MAP["field-thermal-yungas-cluster"]],
        before_after_assets=BeforeAfterAssets(before="Cluster FIRMS previo", after="Cluster FIRMS actual"),
        preview=EVENT_PREVIEW_MAP["event-wildfire-yungas-20260522"],
        visual_state=NarrativeVisualState(pulse=True, highlighted=False),
    ),
    NaturalEventEntity(
        id="event-landslide-volcan-20260522",
        title="Inestabilidad de laderas en Volcan",
        category=NaturalEventCategory.LANDSLIDE,
        kind=NaturalEventCategory.LANDSLIDE,
        event_type=NarrativeEventType.RAINFALL,
        severity=AlertSeverity.MEDIUM,
        status=AlertStatus.ACKNOWLEDGED,
        summary="La humedad superficial y el acumulado reciente elevan la susceptibilidad a remociones menores.",
        short_message="Humedad de ladera en ascenso sobre banquinas expuestas.",
        description="Las laderas aluviales de Volcan presentan humedad superficial elevada y umbrales de lluvia que justifican vigilancia preventiva.",
        long_message="El escenario no muestra colapso inminente, pero si una combinacion persistente de humedad y lluvia que exige seguimiento sobre corredores viales.",
        narrative_label="Vigilancia de laderas",
        narrative_summary="Volcan entra en un modo de vigilancia preventiva: la ladera no rompe aun, pero la humedad y la lluvia acercan el terreno a un umbral sensible.",
        location_name="Volcan · abanicos aluviales",
        region="Volcan",
        observed_at=NOW,
        started_at=NOW,
        updated_at=NOW,
        geometry={
            "type": "Polygon",
            "coordinates": [
                [[-65.46, -23.96], [-65.30, -23.96], [-65.30, -23.84], [-65.46, -23.84], [-65.46, -23.96]]
            ],
        },
        centroid=point(-23.90, -65.38),
        location=point(-23.90, -65.38),
        confidence_score=0.74,
        confidence=DataConfidence.MIXED,
        source_signals=["soil_moisture", "rainfall_anomaly", "slope_model"],
        sources=["smap-l3", "slope-susceptibility-model", "rainfall-anomaly"],
        recommended_actions=[
            "Mantener patrullaje preventivo sobre banquinas",
            "Revisar alcantarillas y drenajes",
            "Actualizar estado vial cada 2 horas",
        ],
        impact_summary={
            "population": "Poblacion dispersa en vigilancia",
            "infrastructure": "Taludes y drenajes lineales sensibles",
            "routes": "Tramo de banquina con control preventivo",
        },
        drivers=["humedad de ladera", "lluvia reciente", "susceptibilidad topografica"],
        factors=["humedad superficial", "lluvia reciente", "abanicos aluviales"],
        metrics=[
            EventMetric(id="soil-moisture", label="Humedad", value="0.71", unit="fraction", trend=EnvironmentalTrend.RISING, emphasis="primary"),
            EventMetric(id="rain-24h-volcan", label="Lluvia 24h", value="82", unit="mm", trend=EnvironmentalTrend.RISING, emphasis="secondary"),
        ],
        related_field_ids=["field-rain-yala-anomaly", "field-soil-volcan-moisture"],
        linked_field_ids=["field-rain-yala-anomaly", "field-soil-volcan-moisture"],
        related_scene_ids=["scene-volcan-slope-watch", "scene-provincial-priority-board"],
        related_fields=[
            NARRATIVE_FIELD_MAP["field-rain-yala-anomaly"],
            NARRATIVE_FIELD_MAP["field-soil-volcan-moisture"],
        ],
        before_after_assets=BeforeAfterAssets(before="Ladera estable reciente", after="Ladera con humedad alta"),
        preview=EVENT_PREVIEW_MAP["event-landslide-volcan-20260522"],
        visual_state=NarrativeVisualState(pulse=False, highlighted=False),
    ),
]

NATURAL_EVENT_MAP = {event.id: event for event in NATURAL_EVENTS}

NARRATIVE_SCENES = [
    NarrativeScene(
        timestamp=TIMELINE_START.replace(day=22),
        available_layers=["ndwi", "flood-risk", "routes"],
        freshness="live",
        comparison_supported=True,
        id="scene-yala-overview-live",
        title="Panoramica hidrica de Yala",
        summary="Escena live para seguir escorrentia, lluvia acumulada y accesos comprometidos.",
        synopsis="La cuenca norte concentra el principal frente hidrico de la jornada.",
        narrative_summary="La escena muestra como el agua ocupa espacio operativo: el rio gana altura, la lluvia sigue cargando la cuenca y los accesos secundarios entran en vigilancia.",
        kind=NarrativeSceneKind.OVERVIEW,
        tone=NarrativeTone.CRITICAL,
        focus_region="Yala",
        captured_at=NOW,
        is_live=True,
        event_ids=["event-flood-yala-20260522"],
        field_ids=["field-river-yala-stage", "field-rain-yala-anomaly"],
        focus_event_ids=["event-flood-yala-20260522"],
        environmental_field_ids=["field-river-yala-stage", "field-rain-yala-anomaly"],
        layer_ids=["ndwi", "flood-risk", "routes"],
        focus_geometry={
            "type": "Polygon",
            "coordinates": [
                [[-65.57, -24.18], [-65.39, -24.18], [-65.39, -24.02], [-65.57, -24.02], [-65.57, -24.18]]
            ],
        },
        viewport={"lat": -24.11, "lng": -65.48, "zoom": 11.2},
        camera=NarrativeSceneCamera(center=(-65.48, -24.11), zoom=11.2, pitch=42.0, bearing=14.0),
        conditions_summary=[
            ConditionsSummaryItem(label="Lluvia", value="148 mm / 24h"),
            ConditionsSummaryItem(label="Rio", value="3.8 m y subiendo"),
            ConditionsSummaryItem(label="Rutas", value="2 accesos sensibles"),
            ConditionsSummaryItem(label="Confianza", value="observada"),
        ],
        headlines=["Cauce en ascenso", "Escorrentia sostenida", "Aviso preventivo"],
        event_previews=[EVENT_PREVIEW_MAP["event-flood-yala-20260522"]],
        events=[NATURAL_EVENT_MAP["event-flood-yala-20260522"]],
        fields=[
            NARRATIVE_FIELD_MAP["field-river-yala-stage"],
            NARRATIVE_FIELD_MAP["field-rain-yala-anomaly"],
        ],
    ),
    NarrativeScene(
        timestamp=TIMELINE_START.replace(day=22),
        available_layers=["firms", "routes"],
        freshness="live",
        comparison_supported=True,
        id="scene-yungas-thermal-response",
        title="Seguimiento de focos en Yungas sur",
        summary="Cruza persistencia FIRMS con cobertura vegetal continua y accesos rurales.",
        synopsis="La energia del frente termico aun es localizada, pero persistente.",
        narrative_summary="La narrativa de fuego se sostiene por continuidad: pocos focos, misma zona y viento moderado, suficiente para mantener el seguimiento activo.",
        kind=NarrativeSceneKind.EVENT_FOCUS,
        tone=NarrativeTone.ESCALATION,
        focus_region="Yungas",
        captured_at=NOW,
        is_live=True,
        event_ids=["event-wildfire-yungas-20260522"],
        field_ids=["field-thermal-yungas-cluster"],
        focus_event_ids=["event-wildfire-yungas-20260522"],
        environmental_field_ids=["field-thermal-yungas-cluster"],
        layer_ids=["firms", "routes"],
        focus_geometry={
            "type": "Polygon",
            "coordinates": [
                [[-64.93, -24.33], [-64.76, -24.33], [-64.76, -24.21], [-64.93, -24.21], [-64.93, -24.33]]
            ],
        },
        viewport={"lat": -24.27, "lng": -64.85, "zoom": 10.6},
        camera=NarrativeSceneCamera(center=(-64.85, -24.27), zoom=10.6, pitch=38.0, bearing=-18.0),
        conditions_summary=[
            ConditionsSummaryItem(label="Focos", value="7 detecciones"),
            ConditionsSummaryItem(label="Viento", value="18 km/h NE"),
            ConditionsSummaryItem(label="Humedad", value="baja"),
            ConditionsSummaryItem(label="Accesos", value="rurales vigilados"),
        ],
        headlines=["Persistencia termica", "Cobertura continua", "Brigadas en prealerta"],
        event_previews=[EVENT_PREVIEW_MAP["event-wildfire-yungas-20260522"]],
        events=[NATURAL_EVENT_MAP["event-wildfire-yungas-20260522"]],
        fields=[NARRATIVE_FIELD_MAP["field-thermal-yungas-cluster"]],
    ),
    NarrativeScene(
        timestamp=TIMELINE_START.replace(day=21),
        available_layers=["flood-risk", "routes"],
        freshness="reciente",
        comparison_supported=True,
        id="scene-volcan-slope-watch",
        title="Laderas inestables en Volcan",
        summary="Monitorea humedad superficial y lluvia sobre pendientes con infraestructura lineal expuesta.",
        synopsis="La vigilancia de ladera sigue un patron preventivo, no de incidente consumado.",
        narrative_summary="El relato territorial en Volcan no es de impacto ya materializado, sino de umbral cercano: humedad y lluvia tensionan laderas y drenajes.",
        kind=NarrativeSceneKind.FIELD_FOCUS,
        tone=NarrativeTone.MONITORING,
        focus_region="Volcan",
        captured_at=NOW,
        is_live=False,
        event_ids=["event-landslide-volcan-20260522"],
        field_ids=["field-rain-yala-anomaly", "field-soil-volcan-moisture"],
        focus_event_ids=["event-landslide-volcan-20260522"],
        environmental_field_ids=["field-rain-yala-anomaly", "field-soil-volcan-moisture"],
        layer_ids=["flood-risk", "routes"],
        focus_geometry={
            "type": "Polygon",
            "coordinates": [
                [[-65.46, -23.96], [-65.30, -23.96], [-65.30, -23.84], [-65.46, -23.84], [-65.46, -23.96]]
            ],
        },
        viewport={"lat": -23.90, "lng": -65.38, "zoom": 11.0},
        camera=NarrativeSceneCamera(center=(-65.38, -23.90), zoom=11.0, pitch=32.0, bearing=8.0),
        conditions_summary=[
            ConditionsSummaryItem(label="Humedad", value="0.71"),
            ConditionsSummaryItem(label="Lluvia", value="82 mm / 24h"),
            ConditionsSummaryItem(label="Taludes", value="sensibles"),
            ConditionsSummaryItem(label="Confianza", value="mixta"),
        ],
        headlines=["Vigilancia preventiva", "Banquinas expuestas", "Drenajes en revision"],
        event_previews=[EVENT_PREVIEW_MAP["event-landslide-volcan-20260522"]],
        events=[NATURAL_EVENT_MAP["event-landslide-volcan-20260522"]],
        fields=[
            NARRATIVE_FIELD_MAP["field-rain-yala-anomaly"],
            NARRATIVE_FIELD_MAP["field-soil-volcan-moisture"],
        ],
    ),
    NarrativeScene(
        timestamp=TIMELINE_START.replace(day=22),
        available_layers=["ndwi", "flood-risk", "firms", "routes"],
        freshness="live",
        comparison_supported=True,
        id="scene-provincial-priority-board",
        title="Tablero provincial de prioridades",
        summary="Agrupa eventos y campos narrativos activos para coordinacion operativa.",
        synopsis="Sintesis provincial para priorizar recursos y lectura territorial comun.",
        narrative_summary="La provincia se ordena en tres relatos operativos simultaneos: agua en Yala, fuego en Yungas y vigilancia de ladera en Volcan.",
        kind=NarrativeSceneKind.RESPONSE,
        tone=NarrativeTone.ESCALATION,
        focus_region="Jujuy",
        captured_at=NOW,
        is_live=True,
        event_ids=[
            "event-flood-yala-20260522",
            "event-wildfire-yungas-20260522",
            "event-landslide-volcan-20260522",
        ],
        field_ids=[
            "field-river-yala-stage",
            "field-rain-yala-anomaly",
            "field-thermal-yungas-cluster",
            "field-soil-volcan-moisture",
        ],
        focus_event_ids=[
            "event-flood-yala-20260522",
            "event-wildfire-yungas-20260522",
            "event-landslide-volcan-20260522",
        ],
        environmental_field_ids=[
            "field-river-yala-stage",
            "field-rain-yala-anomaly",
            "field-thermal-yungas-cluster",
            "field-soil-volcan-moisture",
        ],
        layer_ids=["ndwi", "flood-risk", "firms", "routes"],
        focus_geometry={
            "type": "Polygon",
            "coordinates": [
                [[-66.10, -24.60], [-64.55, -24.60], [-64.55, -23.55], [-66.10, -23.55], [-66.10, -24.60]]
            ],
        },
        viewport={"lat": -24.13, "lng": -65.30, "zoom": 8.2},
        camera=NarrativeSceneCamera(center=(-65.30, -24.13), zoom=8.2, pitch=26.0, bearing=0.0),
        conditions_summary=[
            ConditionsSummaryItem(label="Eventos", value="3 activos"),
            ConditionsSummaryItem(label="Campos", value="4 seguidos"),
            ConditionsSummaryItem(label="Live", value="3 escenas"),
            ConditionsSummaryItem(label="Cobertura", value="provincial"),
        ],
        headlines=["Priorizacion provincial", "Coordinacion multi-riesgo", "Narrativa unificada"],
        event_previews=EVENT_PREVIEWS,
        events=NATURAL_EVENTS,
        fields=ENVIRONMENTAL_FIELDS,
    ),
]

NARRATIVE_SCENE_MAP = {scene.id: scene for scene in NARRATIVE_SCENES}

NARRATIVE_STATUS = NarrativeStatus(
    pipeline_state=ConnectivityState.LIVE,
    active_event_count=len(NATURAL_EVENTS),
    tracked_field_count=len(ENVIRONMENTAL_FIELDS),
    live_scene_count=sum(1 for scene in NARRATIVE_SCENES if scene.is_live),
    last_updated_at=NOW,
    headline="Narrativa territorial activa para Yala, Yungas y Volcan con priorizacion operativa en tiempo casi real.",
    active_event_ids=[event.id for event in NATURAL_EVENTS],
)
